name: CI

on:
  schedule:
    # Run at every 12 hours
    - cron: '0 */12 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          behave

      - name: Generate and upload test report
        run: |
          source venv/bin/activate
          behave -f behave_html_formatter:HTMLFormatter -o reports/report.html
        continue-on-error: true

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: reports/report.html
