name: CI

on:
  schedule:
    # Run at every 12 hours
    - cron: '0 */12 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Check if requirements.txt exists
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt not found"
            exit 1

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        id: run-tests
        run: |
          source venv/bin/activate
          behave

      - name: Generate and upload test report
        run: |
          source venv/bin/activate
          behave -f behave_html_formatter:HTMLFormatter -o reports/report.html
        continue-on-error: true

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: reports/report.html

      - name: Create GitHub issue on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const issueTitle = 'CI Test Failure';
            const issueBody = `
            ## CI Test Failure Report
            The CI run for commit \`${{ github.sha }}\` failed.
            **Branch:** \`${{ github.ref }}\`
            **Workflow:** \`${{ github.workflow }}\`
            **Job:** \`${{ github.job }}\`
            **Run Number:** \`${{ github.run_number }}\`
            **Run ID:** \`${{ github.run_id }}\`

            Check the [Actions tab](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            });
